### ISSUE TITLE
Fix plural words for Emoji and Confetti

### ISSUE THREAD

**Issue by a-trost** [loonywizard/js-confetti#24]
Hey @loonywizard this looks like a super fun library, and I'm gonna take it for a spin on a project I have. 

One thing I've noticed is the spelling of `emojis` as `emojies` which I think should be marked as incorrect. 

![image](https://user-images.githubusercontent.com/19617280/123705433-ef529d80-d834-11eb-8266-3f6d9348cbe3.png)
![image](https://user-images.githubusercontent.com/19617280/123705483-01ccd700-d835-11eb-830a-885fa5bbf650.png)

It seems that `emojis` is the accepted plural of `emoji`. 

Also `confetti` is already plural, and wouldn't be pluralized as `confetties` in properties like `confettiesNumber`. That would still be `confettiNumber`.

**Comment by loonywizard** [comment]
Hi @a-trost, thanks a lot! I'll fix this soon, plural forms here are definitely wrong

**Comment by loonywizard** [comment]
merged https://github.com/loonywizard/js-confetti/pull/26
