### ISSUE TITLE
how to pause/stop animation?

### ISSUE THREAD

**Issue by adnjoo** [loonywizard/js-confetti#27]
is there a way to pause/stop animation?

thanks.

**Comment by loonywizard** [comment]
Hi! currently, there is no way to pause/stop animation

In what scenario do you want to stop confetti animation?

**Comment by adnjoo** [comment]
Hi @loonywizard sorry my bad!

 I had a jsConfetti.addConfetti() happening inside a setInterval function. I just used clearInterval to stop the confetti loop that I had created.
