### ISSUE TITLE
text confetti properties

### ISSUE THREAD

**Issue by 5alidshammout** [loonywizard/js-confetti#29]
I was happy I was able to do this:
![image](https://user-images.githubusercontent.com/73162518/129466148-52597972-5431-44f4-b3bc-bf383a43dd34.png)
using: 
```javascript
const jsConfetti = new JSConfetti();

document.addEventListener('click', () => {
   jsConfetti.addConfetti({
     emojis: [...'5alidshammout'.repeat(10), '👨🏻‍💻'],
     confettiNumber: '5alidshammout'.length,
     confettiRadius: 1,
   });
});
```
but I want to change the font, color and size of the text, can you do that please?

**Comment by loonywizard** [comment]
Hi! Can you implement this feature and open Pull Request?

you need to pass `fontFamily` and `fontColor` args to ConfettiShape constructor and use them in `draw` method

don't forget about default values and TypeScript typings, and please provide an example of usage

**Comment by 5alidshammout** [comment]
how to use the `.draw()` method?

**Comment by loonywizard** [comment]
you don't need to use draw method, it is called by JSConfetti instance

**Comment by 5alidshammout** [comment]
thanks but I really didn't understand, can you show me how to make the text white by changing my code please?

**Comment by loonywizard** [comment]
you need to fork this repo, do changes described in this comment https://github.com/loonywizard/js-confetti/issues/29#issuecomment-900980170 and then create a pull request

After that, I will review changes, and if it is OK I will merge this, otherwise I will leave comments on PR

**Comment by 5alidshammout** [comment]
sorry, I'd really like to contribute to this repo, but I don't know `ts`
