### ISSUE TITLE
Custom canvas element will return error in Typescript

### ISSUE THREAD

**Issue by nazrinnoorzan** [loonywizard/js-confetti#35]
`const jsConfetti = new JSConfetti({ canvas })`

The line of code above will return error in Typescript.
`Expected 0 arguments, but got 1.`

**Comment by loonywizard** [comment]
Hi! thanks a lot for letting me know. Do you want to contribute to the library by fixing it? If not, I will have some free time later this or next week

**Comment by nazrinnoorzan** [comment]
Hi,

Sorry I've removed the package from my project. You can update it on your own.
