### ISSUE TITLE
How to clean up?

### ISSUE THREAD

**Issue by lifenautjoe** [loonywizard/js-confetti#46]
Hi @loonywizard ! 

Thanks for the nice library! 

Question I couldn't find anywhere, how do I clean up the created canvas? Is this done automatically?

Thanks!

**Comment by loonywizard** [comment]
Hi @lifenautjoe !

At the present moment, there is no way to clear a canvas from confetties
Canvas is cleared when all confetties fall down

Do you need such a method? like 

```js
const confetti = new JSConfetti()

confetti.addConfetti()
// ... 

// --->
confetti.clearCanvas()
```

**Comment by stepanjakl** [comment]
Hi, `confetti.clearCanvas()` would be useful. Essentially, there just need to be an id on the canvas and then it can easily be removed from the active DOM.
